name: Transpire Module CI

on:
  workflow_call:
    secrets:
      OCF_CLUSTER_DEPLOY_KEY:
        required: true

jobs:
  build-cluster:
    needs: build-images
    runs-on: ubuntu-latest
    container: harbor.ocf.berkeley.edu/ocf/transpire/transpire:latest
    steps:
      - uses: actions/checkout@v3
        with:
          repository: ocf/kubernetes

      - name: Build cluster repository
        run: transpire object build _out

      - name: Push cluster repository
        run: |
          mkdir $HOME/.ssh
          echo "${{ secrets.OCF_CLUSTER_DEPLOY_KEY }}" > $HOME/.ssh/deploy_key
          chmod 600 $HOME/.ssh/deploy_key
          ssh-keyscan -H github.com > $HOME/.ssh/known_hosts
          export GIT_SSH_COMMAND="ssh -i $HOME/.ssh/deploy_key -o UserKnownHostsFile=$HOME/.ssh/known_hosts"

          CLONE_DIR=$(mktemp -d)
          git clone --bare --single-branch --depth 1 git@github.com:ocf/cluster.git $CLONE_DIR
          mv $CLONE_DIR _out/.git

          cd _out
          git config --bool core.bare false
          git config --bool push.autoSetupRemote true
          git config user.email ocfbot@ocf.berkeley.edu
          git config user.name ocfbot

          git add -A
          git commit -m "chore: rebuild cluster repository" -m "triggered by: ${{ inputs.module_name }}"
          git push
